# -*- coding: utf-8 -*-
"""object_detection(JN)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrenDLfHT3pK8oRjAvFuxRD3AQs0sNKh
"""

!pip install ultralytics

import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO

# Load YOLOv8 model
model = YOLO('/content/yolov8n.pt')  # Replace with the desired model (e.g., yolov8s.pt, yolov8m.pt)

# Load an image for detection
image_path = "/content/235_png.rf.96f2ccad5a0073336edfcccbb9cb06c3.jpg"  # Replace with your image path
image = cv2.imread(image_path)

# Perform detection
results = model(image)

# Display results
annotated_image = results[0].plot()  # Annotate detections on the image
plt.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()

# Save the annotated image
cv2.imwrite("output.jpg", annotated_image)